server: "mobile-hub.lambdatest.com"

common_caps:
  "user": "username"
  "accessKey": "accesskey"
  "project": "First Cucumber Android Project"
  "build": "build-1"
  

browser_caps:
  -
    "platformName": "iOS"
    "platformVersion": "12.0"
    "deviceName": "iPhone 8"
    "app": "lt://"
    "name": "first_test"
    "isRealMobile": "true"
    "geoLocation":"fr"

